
package introsde.finalproject.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExternalAPI", targetNamespace = "http://soap.finalproject.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExternalAPI {


    /**
     * 
     * @param content
     * @param email
     * @param subject
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "sendEmail", targetNamespace = "http://soap.finalproject.introsde/", className = "introsde.finalproject.soap.SendEmail")
    @ResponseWrapper(localName = "sendEmailResponse", targetNamespace = "http://soap.finalproject.introsde/", className = "introsde.finalproject.soap.SendEmailResponse")
    @Action(input = "http://soap.finalproject.introsde/ExternalAPI/sendEmailRequest", output = "http://soap.finalproject.introsde/ExternalAPI/sendEmailResponse")
    public int sendEmail(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "subject", targetNamespace = "")
        String subject,
        @WebParam(name = "content", targetNamespace = "")
        String content);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "quote", targetNamespace = "")
    @RequestWrapper(localName = "getRandomQuote", targetNamespace = "http://soap.finalproject.introsde/", className = "introsde.finalproject.soap.GetRandomQuote")
    @ResponseWrapper(localName = "getRandomQuoteResponse", targetNamespace = "http://soap.finalproject.introsde/", className = "introsde.finalproject.soap.GetRandomQuoteResponse")
    @Action(input = "http://soap.finalproject.introsde/ExternalAPI/getRandomQuoteRequest", output = "http://soap.finalproject.introsde/ExternalAPI/getRandomQuoteResponse")
    public String getRandomQuote();

}
