
package introsde.finalproject.storage.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import introsde.finalproject.soap.Goal;
import introsde.finalproject.soap.GoalType;
import introsde.finalproject.soap.MeasureHistory;
import introsde.finalproject.soap.MeasureType;
import introsde.finalproject.soap.Person;
import introsde.finalproject.soap.Reminder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Storage", targetNamespace = "http://soap.storage.finalproject.introsde/")
@XmlSeeAlso({
    introsde.finalproject.soap.ObjectFactory.class,
    introsde.finalproject.storage.soap.ObjectFactory.class
})
public interface Storage {


    /**
     * 
     * @param measureI
     * @param measureType
     * @param personId
     * @return
     *     returns introsde.finalproject.soap.MeasureHistory
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "registerPersonMeasure", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.RegisterPersonMeasure")
    @ResponseWrapper(localName = "registerPersonMeasureResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.RegisterPersonMeasureResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/registerPersonMeasureRequest", output = "http://soap.storage.finalproject.introsde/Storage/registerPersonMeasureResponse")
    public MeasureHistory registerPersonMeasure(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType,
        @WebParam(name = "measure_i", targetNamespace = "")
        MeasureHistory measureI);

    /**
     * 
     * @param personI
     * @return
     *     returns introsde.finalproject.soap.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "registerPerson", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.RegisterPerson")
    @ResponseWrapper(localName = "registerPersonResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.RegisterPersonResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/registerPersonRequest", output = "http://soap.storage.finalproject.introsde/Storage/registerPersonResponse")
    public Person registerPerson(
        @WebParam(name = "person_i", targetNamespace = "")
        Person personI);

    /**
     * 
     * @param personId
     * @return
     *     returns introsde.finalproject.soap.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "readPersonInfo", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadPersonInfo")
    @ResponseWrapper(localName = "readPersonInfoResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadPersonInfoResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/readPersonInfoRequest", output = "http://soap.storage.finalproject.introsde/Storage/readPersonInfoResponse")
    public Person readPersonInfo(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.finalproject.soap.GoalType>
     */
    @WebMethod
    @WebResult(name = "goalType", targetNamespace = "")
    @RequestWrapper(localName = "readGoalTypes", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadGoalTypes")
    @ResponseWrapper(localName = "readGoalTypesResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadGoalTypesResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/readGoalTypesRequest", output = "http://soap.storage.finalproject.introsde/Storage/readGoalTypesResponse")
    public List<GoalType> readGoalTypes();

    /**
     * 
     * @param goalI
     * @param measure
     * @param personId
     * @param type
     * @return
     *     returns introsde.finalproject.soap.Goal
     */
    @WebMethod
    @WebResult(name = "goal", targetNamespace = "")
    @RequestWrapper(localName = "registerPersonGoal", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.RegisterPersonGoal")
    @ResponseWrapper(localName = "registerPersonGoalResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.RegisterPersonGoalResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/registerPersonGoalRequest", output = "http://soap.storage.finalproject.introsde/Storage/registerPersonGoalResponse")
    public Goal registerPersonGoal(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId,
        @WebParam(name = "measure", targetNamespace = "")
        String measure,
        @WebParam(name = "type", targetNamespace = "")
        String type,
        @WebParam(name = "goal_i", targetNamespace = "")
        Goal goalI);

    /**
     * 
     * @param personId
     * @return
     *     returns java.util.List<introsde.finalproject.soap.Reminder>
     */
    @WebMethod
    @WebResult(name = "reminders-history", targetNamespace = "")
    @RequestWrapper(localName = "readPersonReminders", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadPersonReminders")
    @ResponseWrapper(localName = "readPersonRemindersResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadPersonRemindersResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/readPersonRemindersRequest", output = "http://soap.storage.finalproject.introsde/Storage/readPersonRemindersResponse")
    public List<Reminder> readPersonReminders(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getRandomQuote", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.GetRandomQuote")
    @ResponseWrapper(localName = "getRandomQuoteResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.GetRandomQuoteResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/getRandomQuoteRequest", output = "http://soap.storage.finalproject.introsde/Storage/getRandomQuoteResponse")
    public String getRandomQuote();

    /**
     * 
     * @param personId
     * @param date
     * @return
     *     returns java.util.List<introsde.finalproject.soap.Reminder>
     */
    @WebMethod
    @WebResult(name = "reminder", targetNamespace = "")
    @RequestWrapper(localName = "readPersonRemindersByDate", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadPersonRemindersByDate")
    @ResponseWrapper(localName = "readPersonRemindersByDateResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadPersonRemindersByDateResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/readPersonRemindersByDateRequest", output = "http://soap.storage.finalproject.introsde/Storage/readPersonRemindersByDateResponse")
    public List<Reminder> readPersonRemindersByDate(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId,
        @WebParam(name = "date", targetNamespace = "")
        String date);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "mTypes", targetNamespace = "")
    @RequestWrapper(localName = "readMeasureTypes", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadMeasureTypes")
    @ResponseWrapper(localName = "readMeasureTypesResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadMeasureTypesResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/readMeasureTypesRequest", output = "http://soap.storage.finalproject.introsde/Storage/readMeasureTypesResponse")
    public List<String> readMeasureTypes();

    /**
     * 
     * @param goalId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "removePersonGoal", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.RemovePersonGoal")
    @ResponseWrapper(localName = "removePersonGoalResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.RemovePersonGoalResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/removePersonGoalRequest", output = "http://soap.storage.finalproject.introsde/Storage/removePersonGoalResponse")
    public int removePersonGoal(
        @WebParam(name = "goalId", targetNamespace = "")
        Long goalId);

    /**
     * 
     * @param reminderId
     * @param personId
     * @return
     *     returns introsde.finalproject.soap.Reminder
     */
    @WebMethod
    @WebResult(name = "reminder", targetNamespace = "")
    @RequestWrapper(localName = "readPersonReminder", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadPersonReminder")
    @ResponseWrapper(localName = "readPersonReminderResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadPersonReminderResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/readPersonReminderRequest", output = "http://soap.storage.finalproject.introsde/Storage/readPersonReminderResponse")
    public Reminder readPersonReminder(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId,
        @WebParam(name = "reminderId", targetNamespace = "")
        Long reminderId);

    /**
     * 
     * @param measure
     * @param goalU
     * @param personId
     * @param type
     * @return
     *     returns introsde.finalproject.soap.Goal
     */
    @WebMethod
    @WebResult(name = "goal", targetNamespace = "")
    @RequestWrapper(localName = "editPersonGoal", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.EditPersonGoal")
    @ResponseWrapper(localName = "editPersonGoalResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.EditPersonGoalResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/editPersonGoalRequest", output = "http://soap.storage.finalproject.introsde/Storage/editPersonGoalResponse")
    public Goal editPersonGoal(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId,
        @WebParam(name = "measure", targetNamespace = "")
        String measure,
        @WebParam(name = "type", targetNamespace = "")
        String type,
        @WebParam(name = "goal_u", targetNamespace = "")
        Goal goalU);

    /**
     * 
     * @param measureType
     * @param personId
     * @param date
     * @return
     *     returns introsde.finalproject.soap.MeasureHistory
     */
    @WebMethod
    @WebResult(name = "measurehistory", targetNamespace = "")
    @RequestWrapper(localName = "readPersonMeasurementByDate", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadPersonMeasurementByDate")
    @ResponseWrapper(localName = "readPersonMeasurementByDateResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadPersonMeasurementByDateResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/readPersonMeasurementByDateRequest", output = "http://soap.storage.finalproject.introsde/Storage/readPersonMeasurementByDateResponse")
    public MeasureHistory readPersonMeasurementByDate(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType,
        @WebParam(name = "date", targetNamespace = "")
        String date);

    /**
     * 
     * @param measureType
     * @param personId
     * @param measurehistoryU
     * @return
     *     returns introsde.finalproject.soap.MeasureHistory
     */
    @WebMethod
    @WebResult(name = "measurehistory", targetNamespace = "")
    @RequestWrapper(localName = "editPersonMeasurement", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.EditPersonMeasurement")
    @ResponseWrapper(localName = "editPersonMeasurementResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.EditPersonMeasurementResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/editPersonMeasurementRequest", output = "http://soap.storage.finalproject.introsde/Storage/editPersonMeasurementResponse")
    public MeasureHistory editPersonMeasurement(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType,
        @WebParam(name = "measurehistory_u", targetNamespace = "")
        MeasureHistory measurehistoryU);

    /**
     * 
     * @param reminderI
     * @param personId
     * @return
     *     returns introsde.finalproject.soap.Reminder
     */
    @WebMethod
    @WebResult(name = "reminder", targetNamespace = "")
    @RequestWrapper(localName = "registerPersonReminder", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.RegisterPersonReminder")
    @ResponseWrapper(localName = "registerPersonReminderResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.RegisterPersonReminderResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/registerPersonReminderRequest", output = "http://soap.storage.finalproject.introsde/Storage/registerPersonReminderResponse")
    public Reminder registerPersonReminder(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId,
        @WebParam(name = "reminder_i", targetNamespace = "")
        Reminder reminderI);

    /**
     * 
     * @param reminderU
     * @param personId
     * @return
     *     returns introsde.finalproject.soap.Reminder
     */
    @WebMethod
    @WebResult(name = "reminder", targetNamespace = "")
    @RequestWrapper(localName = "editPersonReminder", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.EditPersonReminder")
    @ResponseWrapper(localName = "editPersonReminderResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.EditPersonReminderResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/editPersonReminderRequest", output = "http://soap.storage.finalproject.introsde/Storage/editPersonReminderResponse")
    public Reminder editPersonReminder(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId,
        @WebParam(name = "reminder_u", targetNamespace = "")
        Reminder reminderU);

    /**
     * 
     * @param reminderId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "removePersonReminder", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.RemovePersonReminder")
    @ResponseWrapper(localName = "removePersonReminderResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.RemovePersonReminderResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/removePersonReminderRequest", output = "http://soap.storage.finalproject.introsde/Storage/removePersonReminderResponse")
    public int removePersonReminder(
        @WebParam(name = "reminderId", targetNamespace = "")
        Long reminderId);

    /**
     * 
     * @param measureType
     * @param personId
     * @return
     *     returns java.util.List<introsde.finalproject.soap.MeasureHistory>
     */
    @WebMethod
    @WebResult(name = "healthProfile-History", targetNamespace = "")
    @RequestWrapper(localName = "readPersonMeasureHistory", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadPersonMeasureHistory")
    @ResponseWrapper(localName = "readPersonMeasureHistoryResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadPersonMeasureHistoryResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/readPersonMeasureHistoryRequest", output = "http://soap.storage.finalproject.introsde/Storage/readPersonMeasureHistoryResponse")
    public List<MeasureHistory> readPersonMeasureHistory(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType);

    /**
     * 
     * @param measureId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "removePersonMeasurement", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.RemovePersonMeasurement")
    @ResponseWrapper(localName = "removePersonMeasurementResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.RemovePersonMeasurementResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/removePersonMeasurementRequest", output = "http://soap.storage.finalproject.introsde/Storage/removePersonMeasurementResponse")
    public int removePersonMeasurement(
        @WebParam(name = "measureId", targetNamespace = "")
        Long measureId);

    /**
     * 
     * @param goalId
     * @param personId
     * @return
     *     returns introsde.finalproject.soap.Goal
     */
    @WebMethod
    @WebResult(name = "goal", targetNamespace = "")
    @RequestWrapper(localName = "readPersonGoal", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadPersonGoal")
    @ResponseWrapper(localName = "readPersonGoalResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadPersonGoalResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/readPersonGoalRequest", output = "http://soap.storage.finalproject.introsde/Storage/readPersonGoalResponse")
    public Goal readPersonGoal(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId,
        @WebParam(name = "goalId", targetNamespace = "")
        Long goalId);

    /**
     * 
     * @param personId
     * @return
     *     returns java.util.List<introsde.finalproject.soap.Goal>
     */
    @WebMethod
    @WebResult(name = "goal-history", targetNamespace = "")
    @RequestWrapper(localName = "readPersonGoals", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadPersonGoals")
    @ResponseWrapper(localName = "readPersonGoalsResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadPersonGoalsResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/readPersonGoalsRequest", output = "http://soap.storage.finalproject.introsde/Storage/readPersonGoalsResponse")
    public List<Goal> readPersonGoals(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId);

    /**
     * 
     * @param measureType
     * @param personId
     * @param measureId
     * @return
     *     returns introsde.finalproject.soap.MeasureHistory
     */
    @WebMethod
    @WebResult(name = "measurehistory", targetNamespace = "")
    @RequestWrapper(localName = "readPersonMeasurement", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadPersonMeasurement")
    @ResponseWrapper(localName = "readPersonMeasurementResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadPersonMeasurementResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/readPersonMeasurementRequest", output = "http://soap.storage.finalproject.introsde/Storage/readPersonMeasurementResponse")
    public MeasureHistory readPersonMeasurement(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType,
        @WebParam(name = "measureId", targetNamespace = "")
        Long measureId);

    /**
     * 
     * @param measure
     * @return
     *     returns introsde.finalproject.soap.MeasureType
     */
    @WebMethod
    @WebResult(name = "mType", targetNamespace = "")
    @RequestWrapper(localName = "readMeasureType", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadMeasureType")
    @ResponseWrapper(localName = "readMeasureTypeResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.ReadMeasureTypeResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/readMeasureTypeRequest", output = "http://soap.storage.finalproject.introsde/Storage/readMeasureTypeResponse")
    public MeasureType readMeasureType(
        @WebParam(name = "measure", targetNamespace = "")
        String measure);

    /**
     * 
     * @param content
     * @param email
     * @param subject
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "sendPersonEmail", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.SendPersonEmail")
    @ResponseWrapper(localName = "sendPersonEmailResponse", targetNamespace = "http://soap.storage.finalproject.introsde/", className = "introsde.finalproject.storage.soap.SendPersonEmailResponse")
    @Action(input = "http://soap.storage.finalproject.introsde/Storage/sendPersonEmailRequest", output = "http://soap.storage.finalproject.introsde/Storage/sendPersonEmailResponse")
    public int sendPersonEmail(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "subject", targetNamespace = "")
        String subject,
        @WebParam(name = "content", targetNamespace = "")
        String content);

}
